# API Keys for Mandrill separetes in enviroments
MANDRILL_API_KEY_PROD: 'HL4ERbuZZO6rrM2nlVjzZg'

# Session Store config/initializers/session_store.rb
SESSION_STORE_URL: 'agendapro.cl'

# Session Store config/environments/production.rb
DEFAULT_URL_OPTIONS: 'agendapro.cl'

# Session Store config/initializers/session_store.rb
PUNTO_PAGOS_API_ENV_PROD: 'production'
PUNTO_PAGOS_API_KEY_PROD: 'nUv0gvi63clwHehLhD7Q'
PUNTO_PAGOS_API_SECRET_PROD: 'pH1ORKDLaL305epH8TrkvXtcxQX5VpCAQAoxLo8K'
