development:
  environment:        'sandbox'
  puntopagos_key:     'rxAeXTifyHgrUAZCeS9i'
  puntopagos_secret:  'QcklPFRnwbJA262I1prThkdx6kkGTH2bBeUu5q6w'
test:
  environment:        'sandbox'
  puntopagos_key:     'rxAeXTifyHgrUAZCeS9i'
  puntopagos_secret:  'QcklPFRnwbJA262I1prThkdx6kkGTH2bBeUu5q6w'
production:
<<<<<<< Updated upstream
  environment:        'production'
  puntopagos_key:     'nUv0gvi63clwHehLhD7Q'
  puntopagos_secret:  'pH1ORKDLaL305epH8TrkvXtcxQX5VpCAQAoxLo8K'
=======
  environment:        ENV["PUNTO_PAGOS_API_ENV_PROD"]
  puntopagos_key:     ENV["PUNTO_PAGOS_API_KEY_PROD"]
  puntopagos_secret:  ENV["PUNTO_PAGOS_API_SECRET_PROD"]
>>>>>>> Stashed changes
