class CreateSparkpostStatusSeeds < ActiveRecord::Migration
  SparkpostStatus.create(event_type: 'bounce', status: 'Rechazado', progress: 0, blacklist: true)
  SparkpostStatus.create(event_type: 'delivery', status: 'Entregado', progress: 2, blacklist: false)
  SparkpostStatus.create(event_type: 'injection', status: 'Enviado', progress: 1, blacklist: false)
  SparkpostStatus.create(event_type: 'spam_complaint', status: 'Enviado a Spam', progress: 0, blacklist: true)
  SparkpostStatus.create(event_type: 'out_of_band', status: 'Error en la entrega', progress: 1, blacklist: false)
  SparkpostStatus.create(event_type: 'policy_rejection', status: 'Rechazado por Protocolo', progress: 0, blacklist: false)
  SparkpostStatus.create(event_type: 'delay', status: 'Entrega Retrasada', progress: 1, blacklist: false)
  SparkpostStatus.create(event_type: 'click', status: 'Click', progress: 2, blacklist: false)
  SparkpostStatus.create(event_type: 'open', status: 'Visualización', progress: 2, blacklist: false)
  SparkpostStatus.create(event_type: 'generation_failure', status: 'Generación Fallida', progress: 0, blacklist: false)
  SparkpostStatus.create(event_type: 'generation_rejection', status: 'Generación Rechazada', progress: 0, blacklist: false)
  SparkpostStatus.create(event_type: 'list_unsubscribe', status: 'Desinscripción', progress: 0, blacklist: true)
  SparkpostStatus.create(event_type: 'link_unsubscribe', status: 'Desinscripción', progress: 0, blacklist: true)
  SparkpostStatus.create(event_type: 'relay_injection', status: 'Enviado', progress: 1, blacklist: false)
  SparkpostStatus.create(event_type: 'relay_rejection', status: 'Rechazado', progress: 0, blacklist: true)
  SparkpostStatus.create(event_type: 'relay_delivery', status: 'Entregado', progress: 2, blacklist: false)
  SparkpostStatus.create(event_type: 'relay_tempfail', status: 'Error Temporal', progress: 1, blacklist: false)
  SparkpostStatus.create(event_type: 'relay_permfail', status: 'Error en la entrega', progress: 0, blacklist: true)
end
